sculpin_content_types:
    episodes:
        permalink: episodes/:basename/
    posts:
        enabled: false
sculpin_twig:
  extensions:
    - ''
    - html
    - twig
    - json
    - html.twig
    - twig.html
